### ISSUE TITLE
Trouble Adding Rooms

### ISSUE THREAD

**Issue by xTACTICSx** [arunoda/meteor-streams#15]
Hey everyone,

I was wondering if this method would be even possible using streams but is it possible to add rooms? I have tried several different ways but I am having trouble getting it to work. Do I need to add clusters? Any help would be greatly appreciated!

**Comment by smmoosavi** [comment]
Can you provide simple API for rooms/channel? like as [socket-io](http://socket.io/docs/rooms-and-namespaces/).
