### ISSUE TITLE
Minor typo in html documentation

### ISSUE THREAD

**Issue by elingerojo** [arunoda/meteor-streams#34]
In http://arunoda.github.io/meteor-streams/security.html there is a typo at the last sentence of the last paragraph.
Were it says:
"If cache turned **of** you can only see..."
Should say:
"If cache turned **on** you can only see..."

**Comment by elingerojo** [comment]
I already made the correction and placed a pull request.

**Comment by arunoda** [comment]
Thanks. But, this project is no longer maintaining.
You should try to use something like this:
https://github.com/YuukanOO/streamy
